output: build

require:
  - bolt
  - bolt_expressions

name: Jumpr

data_pack:
  name: JumprDP
  pack_format: 101
  load:
    - src
  zipped: false

resource_pack:
  name: resources
  pack_format: 84
  load:
    - src
  zipped: false

pipeline:
  - plugins.custom_items
  - plugins.debug_bolt
  - bolt
  - mecha
  - plugins.functions
  - libs.text_components

meta:
  bolt:
    entrypoint: "*"