output: build

name: Jumpr

require:
  - bolt
  - bolt_expressions

data_pack:
  name: datapack
  pack_format: 107.1
  min_format:
    - 107
    - 1
  max_format:
    - 107
    - 1
  load:
    - aj_src
    - src
    - kore_out/jumpr
  zipped: false

resource_pack:
  name: resources
  pack_format: 88.0
  min_format:
    - 88
    - 0
  max_format:
    - 88
    - 0
  load:
    - src
    - kore_out/jumpr
  zipped: false

pipeline:
  - plugins.levels
  - plugins.item_models