output: build

name: Jumpr

require:
  - bolt
  - bolt_expressions

data_pack:
  name: datapack
  pack_format: 97
  load:
    - src
    - kore_out/jumpr
  zipped: false

resource_pack:
  name: resources
  pack_format: 84
  load:
    - src
    - kore_out/jumpr
  zipped: false

pipeline:
  - plugins.levels