# Documentation on libs.versions.toml: https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
kore = "2.0.3-1.21.11-SNAPSHOT"
kotlin = "2.3.20"
kotlinx-io = "0.9.0"

[libraries]
kotlinx-io = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinx-io" }
kore = { module = "io.github.ayfri.kore:kore", version.ref = "kore" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
